# Generated by Django 5.0.3 on 2024-03-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(),
        ),
    ]
